export {BranchesComponent} from './branches/branches.component'
export {BranchComponent} from './branch/branch.component'
export {NewBranchComponent} from './branch/new/new.component'
export {EditBranchComponent} from './branch/edit/edit.component'
export {PartenersComponent} from './parteners/parteners.component'
export {NewPartnerComponent} from './partner/new/new.component'
export {EditPartnerComponent} from './partner/edit/edit.component'
export {PartnerComponent} from './partner/partner.component'